language: php
env:
  global:
    - secure: kUfHHCaTBvPChligjyQmGtvu8jiIa8oROHP3H2mghk8UK5vG0uSNjr7EU3WgDGQpaU34Bup4Z1mpwQ1gY0RUmFN3sVbBzl5JSz4uGci3j+v3dFrCRVmuHxujCCQ/DRBTpSK1SIKBU35CMK5FA4o9M5zrJJor2ydJBE+y+Bm7oPHYkzhTKMmxwb5Lc0KhyBu7g2RPUWcZUJK2rTbosonSH88KVK+Exzcfptx7RYRZPidScDV+6nhTsJyO4gbi8gfR2DmnnLidFgne+4XUUslF/Kafe9HpMEubi/AO76yZm4zielu3+cf947yxSajv9UYF4kgmarphWhz1iSwDQm2Sl6cN1VMsd771wS4mSe6wVvv13EPnDJt7FJ/D6vRHf0VtGUEpxiEUGVkYNkhLj3R7DsQXOr2hp1bX8XOeGe9cq9CPRL/0fStM0c8iQeGZS5WAmCFqQsEIghm4ZnWH0OvCX7HxtL5k2SQGDvSzT3sK1TPm4AA9b6ZSldjy1HV3DAqXW6mtzIzaw0YHmffRIo254Gx3olpX+8TbLhYzluiKsyhDgkmWiywVdsdBLUilk3EMRj+DX9SWkX7R+sTqmwXxRr+1lHjIpdVcsKrckEiz6chVfcmA4M6e7K3VAFY+wVBJ1QhHBdvquFqiNrAHElur2UqDRS1+0aLuT9X257fKTic=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/TEST-NGXUBB-REPO
    - GIT_BRANCH: master
#sudo: required
dist: trusty
matrix:
  include:
    - php: 7.0
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
cache:
  - apt
addons:
  apt:
    packages:
      - realpath
      - mailutils

before_install:
  - export TZ=Africa/Johannesburg

install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --force-yes nginx-extras

script:
  - bash travisCI/install-nginx.sh
  - bash travisCI/run-curl-tests.sh
  #- sudo dpkg --get-selections | grep apache
  - sudo lsof -nPi | grep ":80 (LISTEN)"
  - ls -la /etc/nginx/sites-enabled/
  - bash travisCI/modify-files-and-commit.sh

before_deploy:
  - bash travisCI/deploy-package.sh

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - "conf.d/globalblacklist.conf"
  skip_cleanup: true
  on:
    repo: mitchellkrogza/TEST-NGXUBB-REPO
    tags: false
    branches:
      except:
        - "/^v[0-9]/"
        - "/^V.*$/"
    branches:
       only:
         - "master"
notifications:
  email: false