language: php
env:
  global:
    - secure: unp8irwVXz37jxOFbuM4NciRaq326XktPJP0UuL5m1qdrGiLQVq18cIuXClkxbnCoXzpkL0gG1XdjaD0bRKWAnwRRZBEKDRBYXyF+IcGCfG1k8HUbZoV1OTP21qUXot70YrTiZJ3NkuS32RJdFV9qRAkaM1Srf+ZRHcsZSdXaSJTooMsDLtqk9Bjh9aHEltRCDS0AT2YPANZLW4Yn2QcwBmPhv+3xNxRt2etbl1EYvjYGbKw31JJnMHvS15DJEY52coJ+n4Yw/EI9My4O9TshrAEHeWwXT+dGACdNTD9lXkohuEyc10bgWTGeD5jytm5mbVbzlML3iro0sq6gNWr1iBzGL+FkWSR0ezkbADcnxoUwZa7OHwOPcrzmgkNp6jouGk6Xhl7NQgfwJJtQYPWfOuXIVNUk1Z2Ein/lw2WMzGmEHrqs1x2gIrD83sKqULT3kZBWr4RfhUPjol+V0MZJ+KCW2yo+2C8lZDQ5LWxftoqnG/ia70nFemWsyHSqe2OvN4WfwW9zdS0kRqMZVq/r3R+y0idacFkvO5yXk7cS45tAawIUK5Ipc3fib/ERv8zoDjcIt136hXhlYo44vPr2oprDnyvLcCbdG0A4uCnPpp3Bdbcn2NqIlsXhzBV+YJokaTv5zfWSH2YX6+wdv0C3+dkFjpZaASVg/R7oxg/oXY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/nginx-ultimate-bad-bot-blocker
    - GIT_BRANCH: master
sudo: required
dist: trusty
matrix:
  include:
    - php: 7.0
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
cache:
  - apt
addons:
  apt:
    packages:
      - realpath
      - mailutils

before_install:
  - export TZ=Africa/Johannesburg

install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --force-yes nginx-extras

script:
  - travisCI/install-nginx.sh
  - curl -vsf 'http://localhost:9000/index.php' &> /dev/stdout
  - curl -A "googlebot" http://localhost:9000/index.php &> /dev/stdout
  - curl -A "bingbot" http://localhost:9000/index.php &> /dev/stdout
  - curl -I http://localhost:9000/index.php -e http://google.com
  - STATUSCODE=$(curl -A "80legs" http://localhost:9000/index.php &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi
  - STATUSCODE=$(curl -A "masscan" http://localhost:9000/index.php &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi
  - STATUSCODE=$(curl -I http://localhost:9000/index.php -e http://100dollars-seo.com &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi
  - STATUSCODE=$(curl -I http://localhost:9000/index.php -e http://zx6.ru &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi
  - travisCI/modify-files-and-commit.sh

before_deploy:
  - travisCI/deploy-package.sh

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - "conf.d/globalblacklist.conf"
  skip_cleanup: true
  on:
    repo: mitchellkrogza/nginx-ultimate-bad-bot-blocker
    tags: false
    branches:
      except:
        - "/^v[0-9]/"
        - "/^V.*$/"
    branches:
       only:
         - "master"
notifications:
  email: false